# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class SmzdmItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass

class SmzdmListItem(scrapy.Item):
    article_id = scrapy.Field()
    article_url = scrapy.Field()
    article_title = scrapy.Field()
    article_price = scrapy.Field()
    article_date = scrapy.Field()
    article_format_date = scrapy.Field()
    article_referrals = scrapy.Field()
    article_link = scrapy.Field()
    article_mall_client = scrapy.Field()
    article_link_type = scrapy.Field()
    article_pic = scrapy.Field()
    article_collection = scrapy.Field()
    article_comment = scrapy.Field()
    article_favorite = scrapy.Field()
    article_mall = scrapy.Field()
    article_filter_content = scrapy.Field()
    article_tag = scrapy.Field()
    promotion_type = scrapy.Field()


class SmzdmSingleItem(scrapy.Item):
    article_id = scrapy.Field()
    article_channel_type = scrapy.Field()
    article_url = scrapy.Field()
    article_title_prefix = scrapy.Field()
    article_title = scrapy.Field()
    article_digital_price = scrapy.Field()
    article_price_rmb = scrapy.Field() # 不准，有的压根不是人民币价格
    article_price_level = scrapy.Field()
    article_price = scrapy.Field()
    article_date = scrapy.Field()
    article_format_date = scrapy.Field()
    article_mobile_exclusive = scrapy.Field()
    article_referrals = scrapy.Field()
    article_anonymous = scrapy.Field()
    article_avatar = scrapy.Field()
    article_bl_author_info = scrapy.Field()
    article_top_category = scrapy.Field()
    article_mall_client = scrapy.Field()
    article_link = scrapy.Field()
    article_link_name = scrapy.Field()
    article_link_type = scrapy.Field()
    redirect_data = scrapy.Field()
    article_link_list = scrapy.Field()
    article_pic = scrapy.Field()
    article_small_pic = scrapy.Field()
    article_pic_width = scrapy.Field()
    article_pic_height = scrapy.Field()
    article_format_pic = scrapy.Field()
    article_collection = scrapy.Field()
    article_comment = scrapy.Field()
    article_favorite = scrapy.Field()
    article_worthy = scrapy.Field()
    article_unworthy = scrapy.Field()
    article_mall = scrapy.Field()
    article_mall_id = scrapy.Field()
    article_mall_region = scrapy.Field()
    article_mall_domain = scrapy.Field()
    article_mall_region_name = scrapy.Field()
    article_brand = scrapy.Field()
    article_brand_id = scrapy.Field()
    article_content = scrapy.Field()
    product_intro = scrapy.Field()
    article_content_img_list = scrapy.Field()
    article_comment_open = scrapy.Field()
    share_title = scrapy.Field()
    share_title_other = scrapy.Field()
    share_pic_title = scrapy.Field()
    share_pic = scrapy.Field()
    share_title_separate = scrapy.Field()
    article_order_screenshot = scrapy.Field()
    article_phrase_desc = scrapy.Field()
    article_show_bl_reason = scrapy.Field()
    article_bl_reason = scrapy.Field()
    article_product_focus_pic_url = scrapy.Field()
    article_activity = scrapy.Field()
    article_coupon = scrapy.Field()
    article_edit_page_type = scrapy.Field()
    article_tag = scrapy.Field()
    article_category = scrapy.Field()
    dingyue_tags = scrapy.Field()
    article_comment_switch = scrapy.Field()
    editor_id = scrapy.Field()
    relate_wiki_info = scrapy.Field()
    guess_you_like = scrapy.Field()
    relate_yuanchuang = scrapy.Field()
    tuiguang = scrapy.Field()
    display_mode = scrapy.Field()
    mall_region = scrapy.Field()
    imgmode = scrapy.Field()
    html5_content = scrapy.Field()
    relate_wiki_dingyue = scrapy.Field()


class SmzdmCommentItem(scrapy.Item):
    comment_id = scrapy.Field()
    article_id = scrapy.Field()
    user_id = scrapy.Field()
    user_smzdm_id = scrapy.Field()
    comment_author = scrapy.Field()
    comment_content = scrapy.Field()
    comment_parent = scrapy.Field()
    comment_parent_ids = scrapy.Field()
    support_count = scrapy.Field()
    oppose_count = scrapy.Field()
    comment_date = scrapy.Field()
    format_date = scrapy.Field()
    format_date_client = scrapy.Field()
    ding_class = scrapy.Field()
    post_author = scrapy.Field()
    has_christmas_hat = scrapy.Field()
    floor = scrapy.Field()
    head = scrapy.Field()
    level = scrapy.Field()
    level_logo = scrapy.Field()
    medals = scrapy.Field()
    official = scrapy.Field()
    have_current_user = scrapy.Field()
    is_anonymous = scrapy.Field()
    from_client = scrapy.Field()
    from_client_version = scrapy.Field()
    from_client_uri = scrapy.Field()
    from_client_suff = scrapy.Field()
    total_parent_floors = scrapy.Field()
    parent_data = scrapy.Field() # 不一定都有
