# -*- coding: utf-8 -*-

# Define here the models for your scraped s
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/s.html

import scrapy


class WeixinsmallItem(scrapy.Item):
    # define the fields for your  here like:
    # name =scrapy.Field()
    topic_view_count =scrapy.Field()
    topic_title =scrapy.Field()
    topic_abstract =scrapy.Field()
    topic_ctime_standard =scrapy.Field()
    userName =scrapy.Field()
    topic_id =scrapy.Field()
    homecity =scrapy.Field()
    topic_like_count =scrapy.Field()
    amount =scrapy.Field()
    topic_address =scrapy.Field()
    market_price =scrapy.Field()
    topic_collect_count =scrapy.Field()
    pricetype =scrapy.Field()
    pricetypename =scrapy.Field()
    topic_status =scrapy.Field()
    last_bid_price =scrapy.Field()
    topic_user_id =scrapy.Field()
    topic_url =scrapy.Field()
    user_url =scrapy.Field()
    topic_tags =scrapy.Field()
    user_cell =scrapy.Field()
    user_realname =scrapy.Field()
    dt =scrapy.Field()

class WeixinsmallTakerItem(scrapy.Item):
    topic_id = scrapy.Field()
    total = scrapy.Field()
    user_id = scrapy.Field()
    userName = scrapy.Field()
    order_ctime = scrapy.Field()
    dt = scrapy.Field()
    date = scrapy.Field()

class WeixinsmallTopicInfoItem(scrapy.Item):
    topic_id =scrapy.Field()
    topic_user_id =scrapy.Field()
    topic_order =scrapy.Field()
    topic_view_count =scrapy.Field()
    topic_comment_count =scrapy.Field()
    topic_like_count =scrapy.Field()
    topic_collect_count =scrapy.Field()
    topic_sponsor_count =scrapy.Field()
    topic_title =scrapy.Field()
    topic_abstract =scrapy.Field()
    allowcommenting =scrapy.Field()
    group_members =scrapy.Field()
    price =scrapy.Field()
    market_price =scrapy.Field()
    amount =scrapy.Field()
    topic_bid_hours =scrapy.Field()
    topic_address =scrapy.Field()
    topic_tags =scrapy.Field()
    topic_limited_buying =scrapy.Field()
    topic_sold_amout =scrapy.Field()
    topic_order_price =scrapy.Field()
    scope_level =scrapy.Field()
    pic_count =scrapy.Field()
    status =scrapy.Field()
    sponsor_count =scrapy.Field()
    btn_pricetypename =scrapy.Field()

class WeixinsmallTopicUserInfoItem(scrapy.Item):
    topic_id = scrapy.Field()
    user_id =scrapy.Field()
    user_status =scrapy.Field()
    user_cell =scrapy.Field()
    user_wechat_id =scrapy.Field()
    user_realname =scrapy.Field()
    user_address =scrapy.Field()
    user_email =scrapy.Field()
    user_ctime =scrapy.Field()
    user_level =scrapy.Field()
    user_name =scrapy.Field()
    user_alias =scrapy.Field()
    user_title =scrapy.Field()
    user_follow_count =scrapy.Field()
    user_follower_count =scrapy.Field()
    user_survey_score =scrapy.Field()
    user_relation_count =scrapy.Field()
    user_topic_count =scrapy.Field()
    user_homecity =scrapy.Field()
    userGender =scrapy.Field()
    userRegfrom =scrapy.Field()
    userType =scrapy.Field()
    sceneId =scrapy.Field()
    credit =scrapy.Field()
    userName =scrapy.Field()
    user_quotas =scrapy.Field()
    homecity =scrapy.Field()
    btnfollow =scrapy.Field()

class WeixinsmallbidslstItem(scrapy.Item):
    userName = scrapy.Field()
    user_id = scrapy.Field()
    topic_id = scrapy.Field()
    homecity = scrapy.Field()
    bid_price = scrapy.Field()
    bid_ctime = scrapy.Field()
    bid_status = scrapy.Field()
    bid_statusname = scrapy.Field()
    id = scrapy.Field()

class WeixinsmallSponsorItem(scrapy.Item):
    topic_id=scrapy.Field()
    user_id =scrapy.Field()
    user_status =scrapy.Field()
    user_cell =scrapy.Field()
    user_wechat_id =scrapy.Field()
    user_realname =scrapy.Field()
    user_address =scrapy.Field()
    user_email =scrapy.Field()
    user_secret =scrapy.Field()
    user_ctime =scrapy.Field()
    user_alias =scrapy.Field()
    user_title =scrapy.Field()
    user_follow_count =scrapy.Field()
    user_follower_count =scrapy.Field()
    user_survey_score =scrapy.Field()
    user_relation_count =scrapy.Field()
    user_topic_count =scrapy.Field()
    user_comment_count =scrapy.Field()
    user_homecity =scrapy.Field()
    userGender =scrapy.Field()
    userType =scrapy.Field()
    credit =scrapy.Field()
    user_help_flowers =scrapy.Field()
    userName =scrapy.Field()
    user_quotas =scrapy.Field()